eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
server:
  port: 9998
spring:
  application:
    name: producer-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 100
    initialSize: 2
    maxWait: 60000
    minIdle: 8
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 120000
    validationQuery: SELECT 'x'
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxOpenPreparedStatements: 100
mybatis:
  mapper-locations: classpath:mapper/*.xml
